-- Analytic Registry V1: manual Excel/CSV staging. Select your intended database first.
-- Creates a separate schema and tables only. Does not change registry records.
-- Columns remain nullable so incomplete evidence can be reviewed.
-- StageRowID is generated by SQL Server; it is not a workbook/source identifier.
SET NOCOUNT ON;
IF SCHEMA_ID(N'RegistryExtractV1') IS NULL EXEC(N'CREATE SCHEMA RegistryExtractV1');
GO
-- One observed workspace, Tableau project, or Alteryx collection.
IF OBJECT_ID(N'RegistryExtractV1.Workspaces',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Workspaces] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [PlatformCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [PlatformInstanceKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeScopeKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObservedAt] datetimeoffset(7) NULL,
    [NativeWorkspaceID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeRepositoryID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeWorkspaceType] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [DisplayName] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeOwnerID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeLifecycleCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [CapacityKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL
  );
END;
GO

-- One native report, model, workbook, published source, or Alteryx workflow.
IF OBJECT_ID(N'RegistryExtractV1.Assets',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Assets] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [PlatformCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [PlatformInstanceKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeScopeKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObservedAt] datetimeoffset(7) NULL,
    [NativeAssetID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeRepositoryID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeAssetType] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [AssetTypeCode] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [DisplayName] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeVersionReference] nvarchar(100) COLLATE Latin1_General_100_BIN2 NULL,
    [CreatedByNativeID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ModifiedByNativeID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeOwnerID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [CreatedAtNative] datetimeoffset(7) NULL,
    [ModifiedAtNative] datetimeoffset(7) NULL,
    [NativeLifecycleCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL
  );
END;
GO

-- One physical workspace-to-asset membership.
IF OBJECT_ID(N'RegistryExtractV1.Workspace_Assets',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Workspace_Assets] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [PlatformCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [PlatformInstanceKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeScopeKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObservedAt] datetimeoffset(7) NULL,
    [NativeWorkspaceID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeAssetID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeAssetType] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeAssociationType] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL
  );
END;
GO

-- One native connection.
IF OBJECT_ID(N'RegistryExtractV1.Connections',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Connections] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [PlatformCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [PlatformInstanceKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeScopeKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObservedAt] datetimeoffset(7) NULL,
    [NativeConnectionID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeRepositoryID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeConnectionType] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [DisplayName] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [TechnologyCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [ServerHostname] nvarchar(255) COLLATE Latin1_General_100_BIN2 NULL,
    [Port] int NULL,
    [DatabaseName] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [HasExtract] bit NULL,
    [AuthenticationTypeCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [IdentityClassificationCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [GatewayID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeStatusCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [EvidenceStatusCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL
  );
END;
GO

-- One directly observed asset-to-connection link.
IF OBJECT_ID(N'RegistryExtractV1.Asset_Connections',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Asset_Connections] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [PlatformCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [PlatformInstanceKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeScopeKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObservedAt] datetimeoffset(7) NULL,
    [NativeAssetID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeAssetType] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeConnectionID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [EvidenceStatusCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL
  );
END;
GO

-- One consumer-to-provider asset relationship.
IF OBJECT_ID(N'RegistryExtractV1.Asset_Dependencies',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Asset_Dependencies] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [PlatformCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [PlatformInstanceKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeScopeKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObservedAt] datetimeoffset(7) NULL,
    [NativeAssetID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeAssetType] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [UpstreamNativeAssetID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [UpstreamNativeAssetType] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [UpstreamNativeWorkspaceID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [RelationshipCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [EvidenceStatusCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL
  );
END;
GO

-- One source principal per platform instance, scope, identifier namespace, native ID, and extract.
IF OBJECT_ID(N'RegistryExtractV1.Platform_Users',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Platform_Users] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [PlatformCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [PlatformInstanceKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeScopeKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObservedAt] datetimeoffset(7) NULL,
    [NativePrincipalID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [IdentifierNamespace] nvarchar(60) COLLATE Latin1_General_100_BIN2 NULL,
    [PrincipalTypeCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [DisplayName] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [SourceLogin] nvarchar(320) COLLATE Latin1_General_100_BIN2 NULL,
    [SourceEmail] nvarchar(320) COLLATE Latin1_General_100_BIN2 NULL,
    [SourceStatus] nvarchar(500) COLLATE Latin1_General_100_BIN2 NULL,
    [SourceDirectoryObjectID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [DirectoryTenantKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeRepositoryID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL
  );
END;
GO

-- One directory user per tenant, object ID, and directory extract. Include enabled and disabled users.
IF OBJECT_ID(N'RegistryExtractV1.Directory_Users',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Directory_Users] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [DirectoryTenantKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [DirectoryObjectID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [DisplayName] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [Mail] nvarchar(320) COLLATE Latin1_General_100_BIN2 NULL,
    [UserPrincipalName] nvarchar(320) COLLATE Latin1_General_100_BIN2 NULL,
    [AccountEnabled] bit NULL,
    [ObservedAt] datetimeoffset(7) NULL
  );
END;
GO

-- One observed workspace or asset relationship to a source principal and role. Keep unresolved links.
IF OBJECT_ID(N'RegistryExtractV1.Object_Users',N'U') IS NULL
BEGIN
  CREATE TABLE RegistryExtractV1.[Object_Users] (
    StageRowID bigint IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [RunKey] uniqueidentifier NULL,
    [PlatformCode] nvarchar(30) COLLATE Latin1_General_100_BIN2 NULL,
    [PlatformInstanceKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeScopeKey] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObservedAt] datetimeoffset(7) NULL,
    [NativeObjectType] nvarchar(50) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeObjectID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [ObjectDisplayName] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [PrincipalRoleCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL,
    [SourcePrincipalReference] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [SourceReferenceNamespace] nvarchar(60) COLLATE Latin1_General_100_BIN2 NULL,
    [NativePrincipalID] nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL,
    [IdentifierNamespace] nvarchar(60) COLLATE Latin1_General_100_BIN2 NULL,
    [NativeRole] nvarchar(100) COLLATE Latin1_General_100_BIN2 NULL,
    [SourceEmail] nvarchar(320) COLLATE Latin1_General_100_BIN2 NULL,
    [SourceReferenceStatusCode] nvarchar(40) COLLATE Latin1_General_100_BIN2 NULL
  );
END;
GO
