export type Platform = 'Power BI / Fabric' | 'Tableau' | 'Alteryx';
export type Result = 'Aligned' | 'Pending Implementation' | 'Flagged for Review' | 'Discrepancy' | 'Unable to Verify' | 'Not Applicable';
export type Severity = 'Critical' | 'High' | 'Medium' | 'Low';
export type RequestType = 'Create New' | 'Register Existing' | 'Update Existing' | 'Annual Attestation';
export interface Person { id:string; name:string; email:string; lob:string; manager:string; status:'Active'|'Inactive'|'Unverified' }
export interface Workspace { observationComplete?:boolean; containsPii?: string; containsEuct?: string; highestDmpTier?: string; id:string; nativeId:string; platform:Platform; name:string; businessName:string; purpose:string; ownerId:string; originalOwnerLob:string; lob:string; requesterId:string; configuration:'Standard'|'Custom'; standardVersion:string; lifecycle:string; classification:string; criticality:string; lastAttestation:string; nextAttestation:string; createdDate:string; registryStatus:'Registered'|'Discovered'; contentReadiness:string; requestedVersionId:string; implementedVersionId:string; observedDate:string }
export interface WorkspaceConfigurationVersion { id:string; workspaceId:string; version:number; type:'Standard'|'Custom'; technicalName:string; customReason:string; customExplanation:string; alternateSecurity:string; alternateAuthentication:string; createdDate:string }
export interface ChampionAssignment { configurationVersionId:string; personId:string }
export interface GroupSpecification { businessOwnerId?:string; id:string; configurationVersionId:string; purpose:string; mode:'Existing'|'New'; groupId:string; displayName:string; suggestedName:string; requestedName:string; provisioningStatus:string }
export interface ObservedPrincipal { id:string; workspaceId:string; principalId:string; name:string; kind:'Group'|'User'; accessLevel:string; purpose:string; memberIds:string[]; evidenceDate:string }
export interface EffectiveUserAccess { workspaceId:string; userId:string; accessLevel:string; viaPrincipalId:string }
export interface WorkspaceRequest { supersedesRequestId?:string; createdById?:string; targetDate?:string; execution?:{requestKey:string;implementationReference:string;implementedAt:string;implementedBy:string;verificationReference?:string;verifiedAt?:string;verifiedBy?:string}; containsPii?: string; containsEuct?: string; highestDmpTier?: string; classification:string; criticality:string; id:string; type:RequestType; platform:Platform; workspaceId:string; businessName:string; purpose:string; ownerId:string; configuration:'Standard'|'Custom'; technicalName:string; championIds:string[]; groups:GroupSpecification[]; customReason:string; customExplanation:string; alternateSecurity:string; alternateAuthentication:string; status:'Draft'|'Submitted'; createdDate:string }
export interface Asset { id:string; platform:Platform; type:string; name:string; workspaceId:string|null; nativeId:string; environment:string; version:string; purpose:string; audience:string; developerId:string; championId:string; createdDate:string; modifiedDate:string; lastActivity:string; production:boolean; personalSpace:boolean; assessmentStatus:string; prl:string; euct:string; dmp:string; pii:boolean }
export interface AssetAssessment { prlApprovalReference?:string; prlApprovedBy?:string; id:string; assetId:string; version:string; purpose:string; audience:string; developerId:string; championId:string; solutionLink:string; developmentLink:string; requirementsLink:string; evidenceLink:string; reviewNumber:number; date:string; reviewerId:string; status:string; outcome:string; comments:string; rls:string; processingType:string; datasetSize:string; calculationComplexity:string; sourceCount:number; duration:string; audienceSize:number; prlScore:number; prlTag:string; observedPrlTag:string; euct:string; dmp:string; pii:boolean }
export interface Connection { id:string; name:string; platform:Platform; technology:string; environment:string; hostname:string; port:number; database:string; schema:string; username:string; authenticationType:string; identityClassification:string; credentialReferenceId:string; gatewayId:string; dataSourceId:string; createdBy:string; modifiedDate:string; status:string }
export interface AssetConnection { assetId:string; connectionId:string }
export interface Finding { id:string; workspaceId:string|null; assetId:string|null; connectionId:string|null; bucket:string; rule:string; severity:Severity; result:Result; status:string; firstDetected:string; lastDetected:string; evidence:string; responsibleRole:string; remediation:string; verification:string; platform:Platform }
export interface AdministrativeReview { findingIds?:string[]; closureEvidence?:string; verificationMethod?:string; id:string; type:string; priority:number; severity:Severity; platform:Platform; workspaceId:string|null; assetId:string|null; connectionId:string|null; reason:string; evidenceDate:string; evidenceStatus:string; ownerId:string; lob:string; championGroup:string; reviewerId:string; decision:string; action:string; dueDate:string; status:string; resolution:string; verificationDate:string; notes:string }
export interface Attestation { snapshot?: AttestationSnapshot; followUpReviewId?:string; id:string; workspaceId:string; period:string; dueDate:string; status:string; respondingChampionId:string; date:string; answers:Record<string,string>; changes:string; followUp:string }
export interface DetectionRule { id:string; bucket:string; name:string; description:string }
export interface DetectionCoverage { ruleId:string; platform:Platform; capability:'Available'|'Partial'|'Manual Review Required'|'Not Available'; note:string }
export interface ActivityEvent { id:string; workspaceId:string|null; date:string; actor:string; category:'Requested'|'Implemented'|'Observed'|'Review'|'Attestation'; description:string }
export interface RegistryData { evidencePolicies?:Record<string,number>; approvals?:ApprovalRecord[]; workspaces:Workspace[]; people:Person[]; configurations:WorkspaceConfigurationVersion[]; champions:ChampionAssignment[]; groups:GroupSpecification[]; principals:ObservedPrincipal[]; effectiveAccess:EffectiveUserAccess[]; assets:Asset[]; assessments:AssetAssessment[]; connections:Connection[]; lineage:AssetConnection[]; findings:Finding[]; reviews:AdministrativeReview[]; attestations:Attestation[]; requests:WorkspaceRequest[]; rules:DetectionRule[]; coverage:DetectionCoverage[]; events:ActivityEvent[] }

export interface ApprovalRecord { eligibilityEvidence?:{personId:string;role:string;personStatus:'Active';checkedAt:string;basis:'Prototype role assignment'|'Workspace owner at decision';businessOwnerId?:string}; id:string; targetType:'Request'|'Review'|'Attestation'; targetId:string; purpose:string; contextKey:string; role:string; personId:string; decision:'Approved'|'Changes required'; reference:string; decidedAt:string }
export interface AttestationSnapshot { championIds?:string[]; capturedAt:string; workspace:Workspace; people:Person[]; groups:GroupSpecification[]; assets:Asset[]; connections:Connection[]; findings:Finding[]; events:ActivityEvent[] }
