import { isDateOnly, todayLocal } from './dates';
import type { ApprovalRecord, RegistryData, WorkspaceRequest, AdministrativeReview } from '../types';
export const ownerRoles=['Application Owner','Platform Owner'];
export const closureRoles=['Platform Manager','Platform Team','Platform Owner'];
export const demoRolePeople:Record<string,string[]>={'Application Owner':['P4'],'Platform Owner':['P7'],'Platform Manager':['P8'],'Platform Team':['P2','P3'],'Platform Administrator':['P3']};
export const isAttestationComplete=(status:string)=>status==='Complete'||status==='Complete with follow-up';
export function latestApproval(d:RegistryData,kind:ApprovalRecord['targetType'],targetId:string,purpose:string,contextKey:string){return (d.approvals||[]).filter(a=>a.targetType===kind&&a.targetId===targetId&&a.purpose===purpose&&a.contextKey===contextKey).at(-1);}
export function approvalSatisfied(d:RegistryData,kind:ApprovalRecord['targetType'],targetId:string,purpose:string,contextKey:string,roles:string[]){const a=latestApproval(d,kind,targetId,purpose,contextKey);return !!a&&a.decision==='Approved'&&roles.includes(a.role)&&(a.role==='Business Owner / Workspace Owner'?d.requests.find(r=>r.id===targetId)?.ownerId===a.personId:(demoRolePeople[a.role]||[]).includes(a.personId))&&d.people.some(p=>p.id===a.personId&&p.status==='Active');}
export const requestKey=(r:WorkspaceRequest)=>{const {execution,...intent}=r;return JSON.stringify(intent);};
export const closureKey=(r:AdministrativeReview)=>JSON.stringify([r.resolution,r.verificationDate,r.closureEvidence,r.verificationMethod,r.findingIds||[]]);
export function requestApprovalNeeds(r:WorkspaceRequest,d:RegistryData){const w=d.workspaces.find(w=>w.id===r.workspaceId);const currentGroups=w?d.groups.filter(g=>g.configurationVersionId===w.requestedVersionId):[];const groupChanged=!!w&&r.groups.some(g=>!currentGroups.some(c=>c.purpose===g.purpose&&c.groupId===g.groupId&&c.requestedName===g.requestedName));const needs=[{purpose:'Technical setup',roles:['Platform Administrator']}];if(r.configuration==='Custom')needs.push({purpose:'Custom configuration',roles:ownerRoles});if(r.containsPii==='Yes'||r.classification==='Restricted'||r.classification==='Confidential'||(w&&r.ownerId!==w.ownerId)||groupChanged)needs.push({purpose:'Business ownership / sensitive data / access',roles:['Business Owner / Workspace Owner']});return needs;}
export function validateClosure(r:AdministrativeReview,d:RegistryData){if(!['Resolved','Closed'].includes(r.status))return '';if(!r.resolution.trim()||!r.verificationDate||!r.closureEvidence?.trim())return 'A resolution, verification date, and closing evidence reference are required.';if(!['Subsequent platform observation','Manual verification'].includes(r.verificationMethod||''))return 'Select subsequent platform observation or manual verification.';if(!isDateOnly(r.verificationDate)||r.verificationDate>todayLocal())return 'Verification requires a valid date that is not in the future.';if(r.verificationDate<r.evidenceDate.slice(0,10))return 'Verification cannot predate the evidence under review.';if(!approvalSatisfied(d,'Review',r.id,'Evidence closure',closureKey(r),closureRoles))return 'Closing evidence requires approval by a Platform Manager, Platform Team member, or Platform Owner.';return '';}
