import { initialData } from '../src/data/mock';
import { newRequestGroup } from '../src/utils/requestGroups';
import { validateRequest, comparison, ageDays } from '../src/utils/logic';
import { evidenceState } from '../src/utils/evidence';
import { validateClosure, closureKey } from '../src/utils/approvals';
import type { WorkspaceRequest } from '../src/types';
import { validateAssessment, recordAssessment } from '../src/utils/assessment';
import { saveReview, correctedRequest, requestStage } from '../src/utils/workflow';
import { requestKey } from '../src/utils/approvals';
import { attestationPacket } from '../src/utils/attestation';
import { nextAnnualDate } from '../src/utils/dates';
import { decodeRegistry, persistRegistry, storageKey } from '../src/data/persistence';
let passed=0;const failures:string[]=[];
function check(ok:boolean,label:string){if(ok)passed++;else failures.push(label);}
function rejects(fn:()=>unknown,label:string){let failed=false;try{fn();}catch{failed=true;}check(failed,label);}
const d=structuredClone(initialData);
const r:WorkspaceRequest={id:'AUDIT',type:'Create New',platform:'Power BI / Fabric',workspaceId:'',businessName:'Audit',purpose:'Validate controls',ownerId:'P1',configuration:'Standard',technicalName:'AUDIT_PROD',championIds:['P1'],groups:['Champion','RW','R','Data Sources'].map(p=>newRequestGroup(p,'AUDIT_PROD')),customReason:'',customExplanation:'',alternateSecurity:'',alternateAuthentication:'',status:'Draft',createdDate:'2026-10-01',classification:'Internal',criticality:'Moderate',containsPii:'No',containsEuct:'No',highestDmpTier:'Tier 1'};
check(!validateRequest(r,d).length,'Valid Standard request accepted');
check(validateRequest({...r,ownerId:'MISSING'},d).length>0,'Unknown owner rejected');
check(validateRequest({...r,type:'Update Existing',workspaceId:'WS-005'},d).length>0,'Workspace / platform mismatch rejected');
check(validateRequest({...r,technicalName:''},d).length>0,'Empty technical name rejected');
check(validateRequest({...r,groups:[...r.groups,r.groups[0]]},d).length>0,'Duplicate group purposes rejected');
check(validateRequest({...r,groups:r.groups.map(g=>({...g,requestedName:'SAME_GROUP'}))},d).length>0,'Same group cannot fill different Standard roles');
check(validateRequest({...r,targetDate:'2026-02-30'},d).length>0,'Invalid target date rejected');
check(!evidenceState('2026-02-30',true,365,'2026-10-06').ready,'Impossible observation date rejected');
check(!evidenceState('2026-10-01',true,Infinity,'2026-10-06').ready,'Invalid freshness policy rejected');
check(ageDays('2026-10-01','2026-10-10')===9,'Aging uses supplied current day');
const custom=d.workspaces.find(w=>w.configuration==='Custom')!;
custom.observationComplete=true;d.evidencePolicies={[custom.platform]:365};
check(comparison(custom,d).find(x=>x.field==='Direct user access')?.status==='Unable to Verify','Custom direct access needs an explicit approved baseline');
const w=d.workspaces[0];w.observationComplete=false;
d.principals.find(p=>p.workspaceId===w.id&&p.purpose==='Champion')!.memberIds=[];
check(comparison(w,d).find(x=>x.field==='Champion roster')?.status==='Unable to Verify','Incomplete roster cannot assert mismatch');
const review={...d.reviews[0],status:'Closed',resolution:'Verified',closureEvidence:'TEST',verificationMethod:'Manual verification',verificationDate:'2099-01-01'};
d.approvals=[{id:'TEST',targetType:'Review',targetId:review.id,purpose:'Evidence closure',contextKey:closureKey(review),role:'Platform Manager',personId:'P8',decision:'Approved',reference:'TEST',decidedAt:'2026-10-06T12:00:00Z'}];
check(validateClosure(review,d).length>0,'Future closure evidence rejected despite approval');
check(validateClosure({...review,verificationDate:'2026-02-30'},d).length>0,'Impossible closure date rejected');
const original=d.reviews[0];const responding={...original,status:'Pending Business Response',ownerId:'P1'};
check(saveReview(responding,{...responding,notes:'Owner response'},d,'Investigating',false).status==='Investigating','Owner can respond');
rejects(()=>saveReview(responding,{...responding,resolution:'Unauthorized'},d,'',false),'Business cannot change admin evidence');
rejects(()=>saveReview({...original,status:'Closed'},{...original,status:'Closed',notes:'Changed'},d,'',true),'Closed reviews immutable');
const asset=d.assets[0];
const assessment={...d.assessments[0],assetId:asset.id,id:'AUDIT-ASSESS',version:asset.version,purpose:'Review',developerId:'P1',championId:'P2',reviewerId:'P3',date:'2026-10-01',status:'Complete',outcome:'Approved',sourceCount:1,audienceSize:2,prlScore:1,solutionLink:'',developmentLink:'',requirementsLink:'',evidenceLink:'',pii:!asset.pii};
check(!validateAssessment(assessment,d),'Valid assessment accepted');
check(!!validateAssessment({...assessment,sourceCount:-1},d),'Negative source count rejected');
check(!!validateAssessment({...assessment,date:'2099-01-01'},d),'Future assessment rejected');
check(!!validateAssessment({...assessment,reviewerId:'UNKNOWN'},d),'Unknown assessor rejected');
check(!!validateAssessment({...assessment,evidenceLink:'javascript:alert(1)'},d),'Unsafe reference scheme rejected');
check(recordAssessment(d,{...assessment,version:'HISTORICAL'}).assets[0].pii===asset.pii,'Historical assessment cannot change current classification');
check(recordAssessment(d,{...assessment,status:'In review',outcome:'Pending'}).assets[0].pii===asset.pii,'Draft assessment cannot change current classification');
check(recordAssessment(d,assessment).assets[0].pii===assessment.pii,'Completed current assessment projects classification');
const packet=attestationPacket(d,w.id);const roster=[...(packet.championIds||[])];d.champions=[];
check(packet.championIds?.join()===roster.join(),'Annual packet keeps issued Champion roster');
check(nextAnnualDate('2028-02-29')==='2029-02-28','Leap-day annual date is valid');
const submitted={...r,status:'Submitted' as const};d.requests=[submitted];d.approvals=[{id:'CORRECTION',targetType:'Request',targetId:r.id,purpose:'Technical setup',contextKey:requestKey(submitted),role:'Platform Administrator',personId:'P3',decision:'Changes required',reference:'Fix naming',decidedAt:'2026-10-06T12:00:00Z'}];
check(requestStage(submitted,d)==='Changes required','Correction is a visible stage');
const corrected=correctedRequest(submitted,d,'P1');
check(corrected.id!==submitted.id&&corrected.supersedesRequestId===r.id&&corrected.status==='Draft','Correction preserves submitted identity');
d.requests.push(corrected);check(requestStage(submitted,d)==='Superseded','Superseded request leaves active work');
const raw=JSON.stringify(initialData);check(decodeRegistry(raw).workspaces.length===12,'Saved data remains compatible');
rejects(()=>decodeRegistry('{invalid'),'Malformed storage is detected');
rejects(()=>decodeRegistry('{}'),'Unsupported storage structure is detected');
let stored:string|null=raw;const storage={getItem:(_key:string)=>stored,setItem:(_key:string,value:string)=>{stored=value;}};
persistRegistry(storage,raw,initialData);check(stored===raw,'Valid refresh preserves saved shape');
stored='another-tab';rejects(()=>persistRegistry(storage,raw,initialData),'Cross-tab overwrite blocked');
check(stored==='another-tab','Concurrent data stays unchanged');
console.log(`${passed} audit checks passed; ${failures.length} failed.`);
failures.forEach(f=>console.error('FAIL: '+f));if(failures.length)throw Error('Audit regressions: '+failures.length);
