import assert from 'node:assert/strict';
import {nativeKey,relationshipKey,compareDelivery,resolveEmail,type Observation,type RegistryEvidence,type Delivery} from '../src/domain/foundation';
const base:Observation={platform:'Tableau',instance:'server-a',scope:'site-a',kind:'Asset',nativeType:'Workbook',nativeId:'native-100',name:'Sales',attributes:{revision:'1'}};
const prior:RegistryEvidence={...base,registryId:'registry-900',lastSeenAt:'2026-09-01T12:00:00Z'};
const delivery:Delivery={runKey:'delivery-oct',observedAt:'2026-10-01T12:00:00Z',platform:'Tableau',instance:'server-a',scope:'site-a',kind:'Asset',coverage:'Complete',expectedRows:1,scopeVerified:true};
let n=0;function check(fn:()=>void){fn();n++;}
const renamed:Observation={...base,name:'Renamed'};
check(()=>assert.equal(nativeKey(base),nativeKey(renamed)));
check(()=>assert.notEqual(nativeKey(base),nativeKey({...base,scope:'site-b'})));
check(()=>assert.notEqual(nativeKey(base),nativeKey({...base,nativeId:'NATIVE-100'})));
check(()=>assert.throws(()=>nativeKey({...base,nativeId:''})));
check(()=>assert.notEqual(nativeKey({...base,instance:'a|b',scope:'c'}),nativeKey({...base,instance:'a',scope:'b|c'})));
check(()=>assert.equal(compareDelivery([prior],[{...base,name:'Revenue'}],delivery)[0].registryId,'registry-900'));
check(()=>assert.equal(compareDelivery([prior],[{...base,name:'Revenue'}],delivery)[0].state,'Changed'));
check(()=>assert.deepEqual(compareDelivery([prior],[{...base,attributes:{revision:'2'}}],delivery)[0].changedFields,['revision']));
check(()=>assert.equal(compareDelivery([prior],[base],delivery)[0].state,'Unchanged'));
check(()=>assert.equal(compareDelivery([prior],[{...base,nativeId:'native-200'}],delivery)[0].state,'New'));
check(()=>assert.equal(compareDelivery([prior],[],{...delivery,expectedRows:0})[0].state,'Missing from complete snapshot'));
check(()=>assert.equal(compareDelivery([prior],[],{...delivery,coverage:'Partial',expectedRows:0})[0].state,'Not verified'));
check(()=>assert.equal(compareDelivery([prior],[],{...delivery,coverage:'Failed',expectedRows:null})[0].state,'Not verified'));
check(()=>assert.throws(()=>compareDelivery([prior],[base,base],{...delivery,expectedRows:2})));
check(()=>assert.throws(()=>compareDelivery([prior],[base],{...delivery,expectedRows:2})));
check(()=>assert.throws(()=>compareDelivery([prior],[base],{...delivery,scopeVerified:false})));
check(()=>assert.throws(()=>compareDelivery([prior],[base],{...delivery,observedAt:'2026-10-01'})));
check(()=>assert.throws(()=>compareDelivery([prior],[{...base,scope:'site-b'}],delivery)));
check(()=>assert.equal(compareDelivery([prior],[base],{...delivery,observedAt:'2026-08-01T12:00:00Z'})[0].state,'Older observation'));
check(()=>assert.equal(relationshipKey(base,{...base,nativeId:'b'},'DependsOn'),relationshipKey(renamed,{...base,nativeId:'b'},'DependsOn')));
const directory=[{tenant:'corp',directoryId:'person-1',mail:'alex@example.test',accountEnabled:true}];
check(()=>assert.equal(resolveEmail(' ALEX@example.test ','corp',directory,true).status,'Resolved enabled'));
check(()=>assert.equal(resolveEmail('alex@example.test','other',directory,true).route,'Platform Manager'));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',directory,false).status,'Directory evidence incomplete'));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',[{...directory[0],accountEnabled:false}],true).status,'Resolved disabled'));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',[...directory,{...directory[0],directoryId:'person-2'}],true).status,'Ambiguous directory evidence'));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',[...directory,{...directory[0],accountEnabled:null}],true).status,'Ambiguous directory evidence'));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',[{...directory[0],mail:null}],true).status,'No exact email match'));
check(()=>assert.equal(resolveEmail(null,'corp',directory,true).status,'Missing email or tenant'));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',[{...directory[0],accountEnabled:null}],true).status,'Resolved status unknown'));
check(()=>assert.equal(prior.name,'Sales'));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',[...directory,...directory],true).status,'Ambiguous directory evidence'));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',directory,true,'Group').directoryId,null));
check(()=>assert.equal(resolveEmail('alex@example.test','corp',directory,true,'App').route,'Platform Manager'));
check(()=>assert.equal(nativeKey({...base,kind:'Workspace',nativeType:'PersonalGroup'}),nativeKey({...base,kind:'Workspace',nativeType:'Workspace'})));
check(()=>assert.equal(compareDelivery([prior],[renamed],{...delivery,observedAt:prior.lastSeenAt})[0].state,'Conflicting observation time'));
console.log(`V1.1 foundation: ${n} reconciliation and identity checks passed.`);
