import { initialData } from '../src/data/mock';
import { standardTemplate } from '../src/data/standard';
import { newRequestGroup } from '../src/utils/requestGroups';
import { approvalSatisfied, captureApprovalEligibility, requestApprovalNeeds, requestKey } from '../src/utils/approvals';
import { requestStage } from '../src/utils/workflow';
import { prepareAttestationResponse, recordAssessmentByActor, requestActorIssue } from '../src/utils/workflowActors';
import { attestationPacket, questions } from '../src/utils/attestation';
import { attestationRecipientIds, attestationVisibleTo, currentChampionIds } from '../src/utils/authority';
import { dueAttestations, workItems, workspaceIdsFor } from '../src/utils/workItems';
import type { ApprovalRecord, AssetAssessment, Attestation, WorkspaceRequest } from '../src/types';

let count=0;
function check(ok:boolean,label:string){if(!ok)throw Error(label);count++;}
function rejects(fn:()=>unknown,label:string){let failed=false;try{fn();}catch{failed=true;}check(failed,label);}
const fresh=()=>structuredClone(initialData);
const request:WorkspaceRequest={id:'REQ-V11-ACTOR',type:'Create New',platform:'Power BI / Fabric',workspaceId:'',businessName:'Guarded workflow',purpose:'Validate approval history and command actors.',ownerId:'P1',createdById:'P1',classification:'Internal',criticality:'Low',containsPii:'No',containsEuct:'No',highestDmpTier:'Tier 1',configuration:'Standard',technicalName:'ACTOR_TEST_PROD',championIds:['P1'],groups:standardTemplate.groups.map(group=>newRequestGroup(group.purpose,'ACTOR_TEST_PROD')),customReason:'',customExplanation:'',alternateSecurity:'',alternateAuthentication:'',status:'Submitted',createdDate:'2026-10-01'};
const d=fresh();d.requests=[request];
const receipt:ApprovalRecord={id:'APR-V11',targetType:'Request',targetId:request.id,purpose:'Technical setup',contextKey:requestKey(request),role:'Platform Administrator',personId:'P3',decision:'Approved',reference:'APPROVAL-V11',decidedAt:'2026-10-01T12:00:00Z'};
receipt.eligibilityEvidence=captureApprovalEligibility(d,receipt.role,receipt.personId,receipt.decidedAt);
d.approvals=[receipt];
const delivered={...request,execution:{requestKey:requestKey(request),implementationReference:'CHANGE-V11',implementedAt:'2026-10-02',implementedBy:'P3',verificationReference:'VERIFY-V11',verifiedAt:'2026-10-03',verifiedBy:'P3'}};
check(requestStage(delivered,d)==='Complete','Approved, implemented, and verified request completes');
d.people=d.people.map(person=>person.id==='P3'?{...person,status:'Inactive'}:person);
check(requestStage(delivered,d)==='Complete','A former approver becoming inactive does not reopen completed work');
rejects(()=>captureApprovalEligibility(d,'Platform Administrator','P3',receipt.decidedAt),'Inactive person cannot make a new approval');
d.people=d.people.filter(person=>person.id!=='P3');
check(requestStage(delivered,d)==='Complete','Historical eligibility survives removal of the current directory row');
const legacy={...receipt,eligibilityEvidence:undefined};d.approvals=[legacy];
check(requestStage(delivered,d)==='Complete','Legacy recorded role, date, and reference remain historical facts');
d.approvals=[{...receipt,reference:''}];
check(requestStage(delivered,d)==='Awaiting approval','Receipt without decision evidence is not sufficient');
d.approvals=[{...receipt,decidedAt:'invalid-date'}];
check(requestStage(delivered,d)==='Awaiting approval','Malformed decision date is rejected');
d.approvals=[{...receipt,eligibilityEvidence:{...receipt.eligibilityEvidence!,personId:'P8'}}];
check(requestStage(delivered,d)==='Awaiting approval','Eligibility snapshot must belong to the recorded approver');
d.approvals=[{...receipt,eligibilityEvidence:{...receipt.eligibilityEvidence!,checkedAt:'2026-09-01T12:00:00Z'}}];
check(requestStage(delivered,d)==='Awaiting approval','Eligibility snapshot must match decision time');
d.approvals=[receipt,{...receipt,id:'APR-V11-CORRECT',decision:'Changes required'}];
check(requestStage(delivered,d)==='Changes required','Explicit correction supersedes approval');
d.approvals=[receipt];
check(!approvalSatisfied(d,'Request',request.id,'Technical setup','another revision',['Platform Administrator']),'Changed intent cannot reuse a receipt');
rejects(()=>captureApprovalEligibility(fresh(),'Platform Administrator','P1',receipt.decidedAt),'Active person without the role cannot make a new approval');
check(captureApprovalEligibility(fresh(),'Business Owner / Workspace Owner','P1',receipt.decidedAt,'P1').businessOwnerId==='P1','Eligible owner self-approval remains allowed');

const groupData=fresh();const workspace=groupData.workspaces.find(item=>item.id==='WS-006')!;
const groupRequest={...request,id:'REQ-GROUPS',type:'Update Existing' as const,workspaceId:workspace.id,ownerId:workspace.ownerId,configuration:'Custom' as const,groups:groupData.groups.filter(group=>group.configurationVersionId===workspace.requestedVersionId)};
const accessNeeded=(candidate:WorkspaceRequest)=>requestApprovalNeeds(candidate,groupData).some(need=>need.purpose==='Business ownership / sensitive data / access');
check(!accessNeeded(groupRequest),'Unchanged access set does not add an access approval');
check(accessNeeded({...groupRequest,groups:groupRequest.groups.slice(1)}),'Removing a Custom group requires access approval');
check(accessNeeded({...groupRequest,groups:[...groupRequest.groups,newRequestGroup('Additional','EXTRA')]}),'Adding a group requires access approval');
check(!accessNeeded({...groupRequest,groups:[...groupRequest.groups].reverse()}),'Reordering groups does not alter access intent');
check(!accessNeeded({...groupRequest,groups:groupRequest.groups.map(group=>({...group,id:'copy-'+group.id,displayName:'Refreshed label'}))}),'Internal row IDs and observed labels do not alter access intent');
for(const change of [{groupId:'DIFFERENT-GROUP'},{purpose:'Different entitlement'},{requestedName:'NEW_GROUP_NAME'},{mode:'New' as const}]){
 check(accessNeeded({...groupRequest,groups:groupRequest.groups.map((group,index)=>index===0?{...group,...change}:group)}),'Group identity, purpose, name, and provisioning-mode changes require approval');
}

const actorData=fresh();const draft={...request,status:'Draft' as const,ownerId:'P2',createdById:'P2'};actorData.requests=[draft];
check(!!requestActorIssue(draft,actorData,'P1'),'Direct route cannot let another business profile save or submit a draft');
check(!!requestActorIssue({...draft,ownerId:'P1',createdById:'P1'},actorData,'P1'),'Changing draft ownership cannot grant the editor access');
check(!requestActorIssue(draft,actorData,'P2'),'Stored requester can edit the draft');
check(!requestActorIssue(draft,actorData,'P3'),'Active prototype administrator can edit the draft');
check(!!requestActorIssue({...draft,createdById:'P1'},actorData,'P2'),'The original requester is immutable');
actorData.people=actorData.people.map(person=>person.id==='P2'?{...person,status:'Inactive'}:person);
check(!!requestActorIssue(draft,actorData,'P2'),'Inactive requester cannot make a new save or submission');
actorData.requests=[{...draft,status:'Submitted'}];
check(!!requestActorIssue(draft,actorData,'P3'),'Stale draft cannot overwrite a submitted record');
check(!requestActorIssue({...request,id:'NEW',status:'Draft'},fresh(),'P1'),'New request can identify the current requester');
check(!!requestActorIssue({...request,id:'NEW',status:'Draft',createdById:'P2'},fresh(),'P1'),'New request cannot impersonate another requester');

const annualData=fresh();const packet=attestationPacket(annualData,'WS-001');packet.championIds=['P1','P2'];
const annual:Attestation={id:'ATT-V11',workspaceId:'WS-001',period:'2026',dueDate:'2026-10-30',status:'Not started',respondingChampionId:'',date:'',answers:Object.fromEntries(questions.map((question,index)=>[question,[9,10].includes(index)?'No':'Yes'])),changes:'',followUp:'',snapshot:packet};
annualData.attestations=[annual];
const submitted=prepareAttestationResponse({...annual,respondingChampionId:'P2'},annualData,'P1',true);
check(submitted.respondingChampionId==='P1','Response actor is the current profile, not a selected person');
check(submitted.status==='Pending Owner Approval','Selected Champion submission awaits owner approval');
check(prepareAttestationResponse(annual,annualData,'P2',false).respondingChampionId==='P2','Another selected current profile records its own response');
rejects(()=>prepareAttestationResponse(annual,annualData,'P3',false),'Administrator cannot impersonate a Champion while saving progress');
rejects(()=>prepareAttestationResponse(annual,annualData,'P3',true),'Non-recipient cannot submit an annual response');
rejects(()=>prepareAttestationResponse({...annual,workspaceId:'WS-002'},annualData,'P1',false),'Annual response cannot switch the workspace under review');
rejects(()=>prepareAttestationResponse({...annual,answers:{}},annualData,'P1',true),'Submission requires all applicable answers');
check(prepareAttestationResponse({...annual,answers:{}},annualData,'P1',false).status==='In progress','Eligible Champion can save incomplete progress');
rejects(()=>prepareAttestationResponse({...annual,answers:{...annual.answers,[questions[0]]:'invalid'}},annualData,'P1',true),'Submission rejects unknown answer values');
rejects(()=>prepareAttestationResponse({...annual,answers:{...annual.answers,[questions[0]]:'No'}},annualData,'P1',true),'Exception response needs follow-up context');
annualData.people=annualData.people.map(person=>person.id==='P1'?{...person,status:'Inactive'}:person);
rejects(()=>prepareAttestationResponse(annual,annualData,'P1',false),'Inactive Champion cannot make a new save');
annualData.attestations=[submitted];
rejects(()=>prepareAttestationResponse(annual,annualData,'P2',false),'Stale response cannot overwrite a pending approval packet');
annualData.attestations=[{...submitted,status:'Complete'}];
rejects(()=>prepareAttestationResponse(annual,annualData,'P2',true),'Completed annual responses remain read-only');
const assessmentData=fresh();const assessment:AssetAssessment={...assessmentData.assessments[0],id:'ASM-V11-ACTOR',reviewerId:'P1',dmp:'Tier 1',status:'In review',outcome:'Pending',prlApprovedBy:'Separate evidence approver',prlApprovalReference:'PRL-EXTERNAL'};
check(recordAssessmentByActor(assessmentData,assessment,'P1').assessments.at(-1)?.reviewerId==='P1','Assessment records the current profile as reviewer');
check(recordAssessmentByActor(assessmentData,assessment,'P1').assessments.at(-1)?.prlApprovedBy==='Separate evidence approver','PRL evidence approver remains distinct from the recording reviewer');
rejects(()=>recordAssessmentByActor(assessmentData,{...assessment,reviewerId:'P3'},'P1'),'Assessment cannot attribute the review to another person');
assessmentData.people=assessmentData.people.map(person=>person.id==='P1'?{...person,status:'Inactive'}:person);
rejects(()=>recordAssessmentByActor(assessmentData,assessment,'P1'),'Inactive profile cannot record a new assessment');
const authorityData=fresh();const governed={...authorityData.workspaces[0],ownerId:'P8'};
authorityData.workspaces=[governed];authorityData.requests=[];authorityData.reviews=[];
authorityData.champions=[{configurationVersionId:governed.implementedVersionId,personId:'P2'},{configurationVersionId:governed.requestedVersionId,personId:'P4'}];
const unfrozen={...annual,id:'ATT-AUTHORITY',workspaceId:governed.id,snapshot:undefined};authorityData.attestations=[unfrozen];
check(currentChampionIds(authorityData,governed).join(',')==='P2','Current Champions come from implemented assignments');
check(currentChampionIds(authorityData,{...governed,implementedVersionId:''}).length===0,'Missing implemented version never falls back to requested assignments');
check(workspaceIdsFor(authorityData,'P2').has(governed.id),'Implemented Champion sees the current workspace');
check(!workspaceIdsFor(authorityData,'P4').has(governed.id),'A requested Champion does not gain current workspace responsibility');
check(workspaceIdsFor(authorityData,'P8').has(governed.id),'Current owner retains workspace visibility');
const authorityPacket=attestationPacket(authorityData,governed.id);
check(authorityPacket.championIds?.join(',')==='P2','New annual packet freezes implemented recipients');
check(!authorityPacket.people.some(person=>person.id==='P4'),'Pending Champion is not added to packet participants');
check(authorityPacket.groups.every(group=>group.configurationVersionId===governed.implementedVersionId),'Annual packet captures implemented groups');
check(attestationRecipientIds(unfrozen,authorityData).join(',')==='P2','Unsnapshotted annual review uses current implemented recipients');
rejects(()=>prepareAttestationResponse(unfrozen,authorityData,'P4',false),'Requested-only Champion cannot save an annual response');
const frozen={...unfrozen,snapshot:{...authorityPacket,championIds:['P1']}};authorityData.attestations=[frozen];
check(attestationRecipientIds(frozen,authorityData).join(',')==='P1','Frozen annual recipients override later configuration membership');
check(attestationVisibleTo(frozen,authorityData,'P1'),'Frozen recipient retains annual visibility after current membership changes');
check(!attestationVisibleTo(frozen,authorityData,'P4'),'Pending assignment cannot expose an existing packet');
check(dueAttestations(authorityData,'P1','2026-10-09').length===1,'Frozen recipient retains the due annual work item');
check(dueAttestations(authorityData,'P4','2026-10-09').length===0,'Pending assignment cannot move due annual work to another person');
check(workItems(authorityData,'P1',false).some(item=>item.id===frozen.id&&item.assignedToMe),'Frozen recipient remains assigned to the annual response');
check(!workItems(authorityData,'P4',false).some(item=>item.id===frozen.id),'Pending Champion cannot gain the annual queue item');
check(workItems(authorityData,'P8',false).some(item=>item.id===frozen.id&&!item.assignedToMe),'Current owner may see the annual review without response authority');
rejects(()=>prepareAttestationResponse(frozen,authorityData,'P8',false),'Owner cannot respond unless selected as a recipient');
check(prepareAttestationResponse(frozen,authorityData,'P1',false).respondingChampionId==='P1','Active frozen recipient can still respond');
const emptyPacket={...frozen,snapshot:{...frozen.snapshot,championIds:[]}};authorityData.attestations=[emptyPacket];
check(attestationRecipientIds(emptyPacket,authorityData).length===0,'Explicit empty packet recipients stay empty');
rejects(()=>prepareAttestationResponse(emptyPacket,authorityData,'P2',false),'Empty packet never inherits current implemented recipients');
const legacyPacket={...frozen,snapshot:{...frozen.snapshot,championIds:undefined}};
check(attestationRecipientIds(legacyPacket,authorityData).join(',')==='P2','Legacy packet fallback uses its implemented version only');
check(attestationRecipientIds({...legacyPacket,snapshot:{...legacyPacket.snapshot,workspace:{...governed,implementedVersionId:''}}},authorityData).length===0,'Legacy packet without implemented identity stays unresolved');
console.log(`${count} V1.1 approval, actor, and group-change checks passed.`);
