import assert from 'node:assert/strict';
import {initialData} from '../src/data/mock';
import {comparison,requestIssues} from '../src/utils/logic';
import {annualStatus,workItems,filterWorkItems} from '../src/utils/workItems';
import {accountability} from '../src/utils/accountability';
import type {WorkspaceRequest} from '../src/types';
const d=structuredClone(initialData);d.evidencePolicies={'Power BI / Fabric':365,Tableau:365,Alteryx:365};d.workspaces.forEach(w=>w.observationComplete=true);
let n=0;function check(fn:()=>void){fn();n++;}
const w=d.workspaces[0];
d.champions=d.champions.filter(c=>c.configurationVersionId!==w.requestedVersionId);
d.champions.push({configurationVersionId:w.requestedVersionId,personId:'P4'});
d.principals.find(p=>p.workspaceId===w.id&&p.purpose==='Champion')!.memberIds=['P15'];
check(()=>assert.equal(comparison(w,d).find(x=>x.field==='Champion roster')?.status,'Flagged for Review'));
const a={...d.attestations[0],dueDate:'2026-09-01'};
check(()=>assert.equal(annualStatus({...a,status:'In progress'},'2026-10-09'),'Overdue'));
check(()=>assert.equal(annualStatus({...a,status:'Pending Owner Approval'},'2026-10-09'),'Overdue'));
check(()=>assert.equal(annualStatus({...a,status:'Complete'},'2026-10-09'),'Complete'));
check(()=>assert.equal(accountability(['P15'],d),'Unable to verify'));
check(()=>assert.equal(accountability(['P11'],d),'Confirmed unavailable'));
check(()=>assert.equal(accountability(['P1','P15'],d),'Verified eligible'));
check(()=>assert.equal(accountability([],d),'Missing assignment'));
const groups=d.groups.filter(g=>g.configurationVersionId===w.requestedVersionId);
const r:WorkspaceRequest={id:'TEST',type:'Create New',platform:w.platform,workspaceId:'',businessName:'Example',purpose:'Review',ownerId:'P1',configuration:'Custom',technicalName:'EXAMPLE_PROD',championIds:['P1'],groups:[{...groups[0],mode:'Existing'},{...groups[1],mode:'New',groupId:'',requestedName:groups[0].requestedName}],customReason:'Other',customExplanation:'Example',alternateSecurity:'',alternateAuthentication:'',status:'Draft',createdDate:'2026-10-09',classification:'Internal',criticality:'Moderate',containsPii:'No',containsEuct:'No',highestDmpTier:'Tier 1'};
check(()=>assert.ok(requestIssues(r,d).some(i=>i.message.includes('collide'))));
const review={...d.reviews[0],status:'Investigating',resolution:'Fixed configuration',closureEvidence:'REF-VERIFY',verificationMethod:'Manual verification',verificationDate:'2026-10-09',evidenceDate:'2026-10-01'};
const ready={...d,reviews:[review],approvals:[]};
check(()=>assert.ok(filterWorkItems(workItems(ready,'P3',true),'approval').some(x=>x.id===review.id&&x.nextAction==='Approve closing evidence')));
check(()=>assert.ok(!filterWorkItems(workItems({...ready,reviews:[{...review,closureEvidence:''}]},'P3',true),'approval').some(x=>x.id===review.id)));
console.log(`V1.1 workflow: ${n} checks passed.`);
