import { initialData } from '../src/data/mock';
import { standardTemplate } from '../src/data/standard';
import { newRequestGroup, renameGeneratedGroups } from '../src/utils/requestGroups';
import { annualStatus, dueAttestations, openRequestsFor, filterWorkItems, workItems } from '../src/utils/workItems';
import { requestStage, recordRequestExecution, transitionReview } from '../src/utils/workflow';
import { requestKey } from '../src/utils/approvals';
import { evidenceState } from '../src/utils/evidence';
import type { WorkspaceRequest } from '../src/types';
let count=0;function check(ok:boolean,label:string){if(!ok)throw Error(label);count++;}
function rejects(fn:()=>unknown,label:string){let failed=false;try{fn();}catch{failed=true;}check(failed,label);}
const d=structuredClone(initialData);
const request:WorkspaceRequest={id:'REQ-FLOW',type:'Create New',platform:'Power BI / Fabric',workspaceId:'',businessName:'Flow',purpose:'Evaluate workflow controls',ownerId:'P1',createdById:'P1',classification:'Internal',criticality:'Low',containsPii:'No',containsEuct:'No',highestDmpTier:'Tier 1',configuration:'Standard',technicalName:'TEST_PROD',championIds:['P1'],groups:standardTemplate.groups.map(g=>newRequestGroup(g.purpose,'TEST_PROD')),customReason:'',customExplanation:'',alternateSecurity:'',alternateAuthentication:'',status:'Submitted',createdDate:'2026-10-01'};
d.requests=[request,{...request,id:'REQ-OTHER',ownerId:'P2',createdById:'P2'}];
check(openRequestsFor(d,'P1').length===1,'My requests exclude another owner / creator');
check(requestStage(request,d)==='Awaiting approval','Submitted awaits approval');
rejects(()=>recordRequestExecution(request,d,'implement','CHANGE-1','2026-10-02','P3'),'Cannot implement without approval');
d.approvals=[{id:'APR-FLOW',targetType:'Request',targetId:request.id,purpose:'Technical setup',contextKey:requestKey(request),role:'Platform Administrator',personId:'P3',decision:'Approved',reference:'APPROVAL-1',decidedAt:'2026-10-01T12:00:00Z'}];
check(requestStage(request,d)==='Ready for implementation','Approval does not imply implementation');
rejects(()=>recordRequestExecution(request,d,'verify','VERIFY-1','2026-10-03','P3'),'Cannot verify before implementation');
rejects(()=>recordRequestExecution(request,d,'implement','CHANGE-1','2026-10-02','P1'),'Business role cannot record implementation');
rejects(()=>recordRequestExecution(request,d,'implement','CHANGE-1','2026-02-30','P3'),'Invalid calendar date blocked');
const implemented=recordRequestExecution(request,d,'implement','CHANGE-1','2026-10-02','P3');
check(requestStage(implemented,d)==='Awaiting verification','Recorded implementation still needs verification');
check(requestKey(implemented)===requestKey(request),'Delivery evidence does not invalidate intent approval');
rejects(()=>recordRequestExecution(implemented,d,'verify','VERIFY-1','2026-10-01','P3'),'Verification cannot predate implementation');
const verified=recordRequestExecution(implemented,d,'verify','VERIFY-1','2026-10-03','P3');
check(requestStage(verified,d)==='Complete','Verification completes lifecycle');
check(requestStage({...verified,purpose:'Changed scope'},d)==='Awaiting approval','Changed intent requires fresh approval');
d.requests=[verified];check(openRequestsFor(d,'P1').length===1,'Verified new workspace remains open until linked to the registry');
check(workItems(d,'P1',false).some(i=>i.id===verified.id&&i.status==='Awaiting registry link'),'Unlinked delivery has an explicit reconciliation task');
const ds=newRequestGroup('Data Sources','OLD_PROD');const custom={...newRequestGroup('RW','OLD_PROD'),requestedName:'MANUAL_RW'};
const renamed=renameGeneratedGroups([ds,custom],'NEW_PROD');
check(renamed[0].requestedName==='NEW_PROD_DS','Generated DS follows technical name');check(renamed[1].requestedName==='MANUAL_RW','Manual group names retained');
check(standardTemplate.groups.length===4,'Four Standard groups');
check(evidenceState('2026-10-01',true,7,'2026-10-06').ready,'Complete fresh evidence ready');
check(evidenceState('2026-09-01',true,7,'2026-10-06').status==='Stale','Stale evidence identified');
check(!evidenceState('2026-10-06',undefined,7,'2026-10-06').ready,'Unknown completeness cannot imply alignment');
check(!evidenceState('2026-10-06',true,undefined,'2026-10-06').ready,'No freshness policy cannot imply alignment');
check(!evidenceState('2026-10-07',true,7,'2026-10-06').ready,'Future timestamp cannot imply current evidence');
const att=d.attestations.find(a=>a.status!=='Complete')!;
d.attestations=[{...att,id:'DUE',workspaceId:'WS-001',status:'Not started',dueDate:'2026-10-20'},{...att,id:'LATER',workspaceId:'WS-001',status:'Not started',dueDate:'2026-12-20'},{...att,id:'OLD',workspaceId:'WS-001',status:'Not started',dueDate:'2026-10-01'}];
check(dueAttestations(d,'P1','2026-10-06').map(a=>a.id).join(',')==='OLD,DUE','Due card includes overdue and next 30 days only');
const items=workItems(d,'P1',false);check(filterWorkItems(items,'overdue','2026-10-06').every(i=>i.due&&i.due<'2026-10-06'),'Overdue excludes missing and future dates');
check(filterWorkItems(items,'assigned').every(i=>i.assignedToMe),'Assigned view uses a single predicate');
const review=d.reviews.find(r=>r.status==='New')!;
rejects(()=>transitionReview(review,d,'Closed',true),'Cannot close a new review without investigation');
rejects(()=>transitionReview(review,d,'Investigating',false),'Business cannot advance admin stages');
check(transitionReview(review,d,'Investigating',true).status==='Investigating','Explicit investigation action works');
check(annualStatus({...att,status:'Overdue',answers:{},dueDate:'2026-10-30'},'2026-10-06')==='Not started','Future annual reviews are not labelled overdue');
const waiting={...review,status:'Pending Business Response',ownerId:'P1',notes:'Business owner confirmed the requested correction.'};
check(transitionReview(waiting,d,'Investigating',false).status==='Investigating','Business response returns work to investigator');
rejects(()=>transitionReview({...waiting,notes:''},d,'Investigating',false),'Empty business response rejected');
rejects(()=>transitionReview({...waiting,ownerId:'P2'},d,'Investigating',false),'Another business owner cannot respond');
console.log(`${count} workflow checks passed.`);
