import { useState } from 'react';
import { useRegistry, event } from '../data/store';
import { platforms } from '../data/mock';
import { Panel, Field, Note } from './ui';
export function EvidenceSettings() {
  const {data,update,viewMode,setNotice}=useRegistry();const [limits,setLimits]=useState<Record<string,string>>(Object.fromEntries(platforms.map(p=>[p,String(data.evidencePolicies?.[p]||'')])));
  const [workspaceId,setWorkspaceId]=useState('');const [complete,setComplete]=useState('');const [error,setError]=useState('');
  function save(){if(platforms.some(p=>limits[p]&&(!Number.isInteger(Number(limits[p]))||Number(limits[p])<1||Number(limits[p])>365))){setError('Freshness limits must be whole days from 1 to 365, or blank.');return;}
    if(!update(d=>({...d,evidencePolicies:Object.fromEntries(platforms.filter(p=>limits[p]).map(p=>[p,Number(limits[p])])),workspaces:d.workspaces.map(w=>w.id===workspaceId?{...w,observationComplete:complete===''?undefined:complete==='Complete'}:w),events:[...d.events,event('Prototype evidence rules / completeness metadata updated.','Observed',workspaceId||null)] })))return;setError('');setNotice('Evidence rules saved for this prototype. Observation timestamps are unchanged.');}
  return <Panel title="Evidence rules" subtitle="Freshness and completeness are separate from risk severity."><div className="panel-body"><Note>Set agreed platform limits here. Blank limits and unknown completeness cannot confirm alignment. These settings simulate ingestion metadata; they do not collect new evidence.</Note><fieldset disabled={viewMode!=='Administrator'} className="form-fieldset"><div className="form-grid">{platforms.map(p=><Field label={p+' · maximum age (days)'} key={p}><input type="number" min={1} max={365} value={limits[p]} placeholder="Not configured" onChange={e=>setLimits({...limits,[p]:e.target.value})}/></Field>)}<Field label="Workspace extract"><select value={workspaceId} onChange={e=>{setWorkspaceId(e.target.value);const w=data.workspaces.find(w=>w.id===e.target.value);setComplete(w?.observationComplete===undefined?'':w.observationComplete?'Complete':'Incomplete');}}><option value="">Choose a workspace…</option>{data.workspaces.map(w=><option key={w.id} value={w.id}>{w.businessName}</option>)}</select></Field><Field label="Extract completeness"><select value={complete} disabled={!workspaceId} onChange={e=>setComplete(e.target.value)}><option value="">Unknown</option><option>Complete</option><option>Incomplete</option></select></Field></div>{error&&<p className="validation" role="alert">{error}</p>}<button className="primary" onClick={save}>Save evidence rules</button></fieldset></div></Panel>;
}
