import type { ReactNode } from 'react';
import { ArrowUpRight, Search, ChevronRight, Info } from 'lucide-react';
import { Link } from 'react-router-dom';
export function Badge({children}:{children:ReactNode}){const s=String(children);const tone=/Not Available|Unable to [Vv]erify|Unavailable|Unclassified|Unassigned|Unknown/.test(s)?'gray':/Incomplete|Rule needed|Changes required/.test(s)?'amber':/Critical|Discrepancy|Inactive|Overdue|At Risk|High|Action Required/.test(s)?'red':/Pending|Partial|Flagged|Medium|In progress|Investigating|Custom|Unverified/.test(s)?'amber':/Aligned|Complete|Active|Ready|Available|Standard|Registered|Approved|Resolved/.test(s)?'green':'gray';return <span className={`badge ${tone}`}><i/>{children}</span>}
export function PlatformMark({platform}:{platform:string}){return <span className={'platform-mark '+(platform==='Tableau'?'tableau':platform==='Alteryx'?'alteryx':'powerbi')}>{platform==='Tableau'?'✣':platform==='Alteryx'?'a':'▥'}</span>}
export function Title({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:ReactNode}){return <div className="page-title"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="actions">{actions}</div></div>}
export function Panel({title,subtitle,actions,children,className=''}:{title?:string;subtitle?:string;actions?:ReactNode;children:ReactNode;className?:string}){return <section className={'panel '+className}>{title&&<div className="panel-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{actions}</div>}{children}</section>}
export function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Select({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label?:string}){return <select aria-label={label||(options[0]?.startsWith('All ')?options[0]:undefined)} value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select>}
export function SearchInput({value,onChange,placeholder='Search…'}:{value:string;onChange:(s:string)=>void;placeholder?:string}){return <div className="search"><Search size={16}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function Empty({text='No records match these filters.'}:{text?:string}){return <div className="empty">{text}</div>}
export function Note({children,tone='info'}:{children:ReactNode;tone?:string}){return <div className={'note '+tone}><Info size={17}/><div>{children}</div></div>}
export function Metric({label,value,detail,to}:{label:string;value:number|string;detail?:string;to?:string}){const content=<><div className="metric-label">{label}{to&&<ArrowUpRight size={16}/>}</div><strong>{value}</strong>{detail&&<small>{detail}</small>}</>;return to?<Link className="metric" to={to}>{content}</Link>:<div className="metric">{content}</div>}
export function KV({label,children}:{label:string;children:ReactNode}){return <div className="kv"><small>{label}</small><div>{children||'—'}</div></div>}
export function Trail({items}:{items:{label:string;to?:string}[]}){return <div className="breadcrumbs">{items.map((i,n)=><span key={n}>{n>0&&<ChevronRight size={12}/ >}{i.to?<Link to={i.to}>{i.label}</Link>:i.label}</span>)}</div>}
export function Bars({items}:{items:{label:string;value:number;color?:string}[]}){const max=Math.max(...items.map(i=>i.value),1);return <div className="bars">{items.map(i=><div className="bar-row" key={i.label}><span>{i.label}</span><div className="bar-track"><i style={{width:`${i.value/max*100}%`,background:i.color}}/></div><strong>{i.value}</strong></div>)}</div>}
